// Generated by https://quicktype.io

import { ClashProxyItem } from '$clash-utils'

export interface ClashConfig {
  'proxies': ClashProxyItem[]
  'proxy-groups': ProxyGroup[]
  'proxy-providers': ProxyProviders | undefined
  'port': number
  'socks-port': number
  'mixed-port': number
  'allow-lan': boolean
  'bind-address': string
  'mode': string
  'log-level': string
  'ipv6': boolean
  'external-controller': string
  'interface-name': string
  'hosts': null
  'dns': DNS
  'rules': string[]
}

export interface DNS {
  'enable': boolean
  'listen': string
  'default-nameserver': string[]
  'enhanced-mode': string
  'fake-ip-range': string
  'nameserver': string[]
  'fallback-filter': FallbackFilter
}

export interface FallbackFilter {
  geoip: boolean
  ipcidr: null
}

export interface ProxyGroup {
  name: string
  use?: string[]
  proxies: string[]
  type: ProxyGroupType
  url?: string
  interval?: number
  filter?: string
}

export enum ProxyGroupType {
  Fallback = 'fallback',
  Select = 'select',
  URLTest = 'url-test',
}

export interface ProxyProviders {
  [name: string]: ProxyProvider
}

export interface ProxyProvider {
  'type': 'file' | 'http'
  'path': string
  'url'?: string
  'interval'?: number
  'health-check': ProxyProviderHealthCheck
}

export interface ProxyProviderHealthCheck {
  enable: boolean
  url: string
}
