packages:
  - packages/**

ignoreBuiltDependencies:
  - less

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - electron
  - esbuild
  - tldjs
  - unrs-resolver

publicHoistPattern:
  - '*unocss*' # place uno.config.ts anywhere
