packages:
  - packages/**

overrides:
  ant-float-label>antd: '6'
  ant-float-label>react: '19'
  ant-float-label>react-dom: '19'

ignoreBuiltDependencies:
  - less

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - electron
  - esbuild
  - tldjs
  - unrs-resolver

publicHoistPattern:
  - '*unocss*' # place uno.config.ts anywhere
