packages:
  - packages/**

allowBuilds:
  '@swc/core': true
  core-js: true
  electron: true
  electron-winstaller: false
  esbuild: true
  less: false
  tldjs: true
  unrs-resolver: true
ignoreWorkspaceRootCheck: true
includeWorkspaceRoot: true
minimumReleaseAge: 1440 # for ncu

publicHoistPattern:
  - '*unocss*' # place uno.config.ts anywhere

