// Generated by https://quicktype.io

import { ClashProxyItem } from '$clash-utils'

export default interface ClashConfig {
  'proxies': ClashProxyItem[]
  'proxy-groups': ProxyGroup[]
  'port': number
  'socks-port': number
  'mixed-port': number
  'allow-lan': boolean
  'bind-address': string
  'mode': string
  'log-level': string
  'ipv6': boolean
  'external-controller': string
  'interface-name': string
  'hosts': null
  'dns': DNS
  'rules': string[]
}

export interface DNS {
  'enable': boolean
  'listen': string
  'default-nameserver': string[]
  'enhanced-mode': string
  'fake-ip-range': string
  'nameserver': string[]
  'fallback-filter': FallbackFilter
}

export interface FallbackFilter {
  geoip: boolean
  ipcidr: null
}

export interface ProxyGroup {
  name: string
  proxies: string[]
  type: ProxyGroupType
  url?: string
  interval?: number
  filter?: string
}

export enum ProxyGroupType {
  Fallback = 'fallback',
  Select = 'select',
  URLTest = 'url-test',
}
